У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [18]:
import pandas as pd
df = pd.read_csv('tips.csv')

In [19]:
df.head()   # Перші 5 рядків

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
df.shape   # Розмір датасету

(244, 7)

In [21]:
df.columns   # Назви всіх колонок

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [23]:
df.info()   # типи даних датасету: float64(2), int64(1), str(4)

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [36]:
df.total_bill   # Колонкa `total_bill`

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [37]:
df[['total_bill', 'tip']]   # Колонки `total_bill` та `tip` разом

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [38]:
df.head(11)   # Перші 10 рядків

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2

In [39]:
df.loc[5]   # Рядок з індексом 5

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [60]:
bill_20 = df[(df['total_bill'] > 20.0)]   # Всі рахунки більше 20 доларів

In [61]:
display(bill_20)   
display(f'Всього знайдено {len(bill_20)} рахунків більше 20 доларів')
display(bill_20.head(5))   # перші 5 записів відфільтрованого набору

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

'Всього знайдено 97 рахунків більше 20 доларів'

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [62]:
women = df[(df['sex'] == 'Female')]   # Всі відвідувачі-жінки

In [64]:
display(women)
display(f'Всього {len(women)} відвідувачів були жіночої статі')
display(women.head(5))   # перші 5 записів відфільтрованого набору

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

'Всього 87 відвідувачів були жіночої статі'

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [65]:
supper = df[(df['time'] == 'Dinner')]   # час - вечір

In [66]:
display(supper)
display(f'Всього {len(supper)} рахунків були оплачені ввечері')
display(supper.head(5))   # перші 5 записів відфільтрованого набору

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

'Всього 176 рахунків були оплачені ввечері'

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [67]:
exp_supper = df[(df['time'] == 'Dinner') & (df['total_bill'] > 30.0)]   # Рахунки на вечерю з сумою чеку більше 30 доларів

In [69]:
display(exp_supper)
display(f'Всього {len(exp_supper)} рахунків були більше 30 доларів та оплачені ввечері')
display(exp_supper.head(5))   # перші 5 записів відфільтрованого набору

     total_bill    tip     sex smoker  day    time  size
11        35.26   5.00  Female     No  Sun  Dinner     4
23        39.42   7.58    Male     No  Sat  Dinner     4
39        31.27   5.00    Male     No  Sat  Dinner     3
44        30.40   5.60    Male     No  Sun  Dinner     4
47        32.40   6.00    Male     No  Sun  Dinner     4
52        34.81   5.20  Female     No  Sun  Dinner     4
56        38.01   3.00    Male    Yes  Sat  Dinner     4
59        48.27   6.73    Male     No  Sat  Dinner     4
95        40.17   4.73    Male    Yes  Fri  Dinner     4
102       44.30   2.50  Female    Yes  Sat  Dinner     3
112       38.07   4.00    Male     No  Sun  Dinner     3
156       48.17   5.00    Male     No  Sun  Dinner     6
167       31.71   4.50    Male     No  Sun  Dinner     4
170       50.81  10.00    Male    Yes  Sat  Dinner     3
173       31.85   3.18    Male    Yes  Sun  Dinner     2
175       32.90   3.11    Male    Yes  Sun  Dinner     2
179       34.63   3.55    Male    Yes  Sun  Dinner     2
180       34.65   3.68    Male    Yes  Sun  Dinner     4
182       45.35   3.50    Male    Yes  Sun  Dinner     3
184       40.55   3.00    Male    Yes  Sun  Dinner     2
187       30.46   2.00    Male    Yes  Sun  Dinner     5
207       38.73   3.00    Male    Yes  Sat  Dinner     4
210       30.06   2.00    Male    Yes  Sat  Dinner     3
212       48.33   9.00    Male     No  Sat  Dinner     4
219       30.14   3.09  Female    Yes  Sat  Dinner     4
237       32.83   1.17    Male    Yes  Sat  Dinner     2
238       35.83   4.67  Female     No  Sat  Dinner     3

'Всього 27 рахунків були більше 30 доларів та оплачені ввечері'

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [72]:
mean_check = df.total_bill.mean().round(2)
display(f'Середній розмір рахунку cкладає: ${mean_check}')

'Середній розмір рахунку cкладає: $19.79'

In [77]:
max_tip = df.tip.max()
display(f'Максимальні чайові були: ${max_tip}')

'Максимальні чайові були: $10.0'

In [85]:
is_empty = df.isna().sum()
display(is_empty)   # Порожні клітинки відсутні у даному датасеті

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [116]:
lunch_ = len(df[(df['time'] == 'Lunch')])
dinner_ = len(df[(df['time'] == 'Dinner')])
together = len(df['time'].isin(['Lunch', 'Dinner']))

In [117]:
display(f'За обіди: {lunch_} рахунків')
display(f'За вечері: {dinner_} рахунків')
display(f'Разом рахунків за обіди і вечері: {together}')

'За обіди: 68 рахунків'

'За вечері: 176 рахунків'

'Разом рахунків за обіди і вечері: 244'

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [144]:
mean_bill_by_sex = df.groupby('sex')['total_bill'].mean().round(2)
mean_tips_by_day = df.groupby('day')['tip'].mean().round(2)
clients_by_day = df.groupby('day')['size'].sum()

In [145]:
display(mean_bill_by_sex)   # Середній рахунок за статтю (groupby sex)

sex
Female    18.06
Male      20.74
Name: total_bill, dtype: float64

In [146]:
display(mean_tips_by_day)   # Середні чайові за днем тижня (groupby day)

day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64

In [147]:
display(clients_by_day)   # Відвідувачів у кожен день

day
Fri      40
Sat     219
Sun     216
Thur    152
Name: size, dtype: int64

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [153]:
df['tip_percentage'] = ((df['tip'] * 100) / df['total_bill']).round(1)

In [155]:
df['tip_percentage'].head(11)

0      5.9
1     16.1
2     16.7
3     14.0
4     14.7
5     18.6
6     22.8
7     11.6
8     13.0
9     21.9
10    16.7
Name: tip_percentage, dtype: float64

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [161]:
sorted_bills = df.sort_values('total_bill', ascending = True)
sorted_tips = df.sort_values('tip', ascending = False)

In [162]:
sorted_bills   # За розміром рахунку (зростання)

     total_bill    tip     sex smoker   day    time  size  tip_percentage
67         3.07   1.00  Female    Yes   Sat  Dinner     1            32.6
92         5.75   1.00  Female    Yes   Fri  Dinner     2            17.4
111        7.25   1.00  Female     No   Sat  Dinner     1            13.8
172        7.25   5.15    Male    Yes   Sun  Dinner     2            71.0
149        7.51   2.00    Male     No  Thur   Lunch     2            26.6
..          ...    ...     ...    ...   ...     ...   ...             ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3             7.7
156       48.17   5.00    Male     No   Sun  Dinner     6            10.4
59        48.27   6.73    Male     No   Sat  Dinner     4            13.9
212       48.33   9.00    Male     No   Sat  Dinner     4            18.6
170       50.81  10.00    Male    Yes   Sat  Dinner     3            19.7

[244 rows x 8 columns]

In [163]:
sorted_tips   # За чайовими (спадання)

     total_bill    tip     sex smoker   day    time  size  tip_percentage
170       50.81  10.00    Male    Yes   Sat  Dinner     3            19.7
212       48.33   9.00    Male     No   Sat  Dinner     4            18.6
23        39.42   7.58    Male     No   Sat  Dinner     4            19.2
59        48.27   6.73    Male     No   Sat  Dinner     4            13.9
141       34.30   6.70    Male     No  Thur   Lunch     6            19.5
..          ...    ...     ...    ...   ...     ...   ...             ...
0         16.99   1.01  Female     No   Sun  Dinner     2             5.9
111        7.25   1.00  Female     No   Sat  Dinner     1            13.8
92         5.75   1.00  Female    Yes   Fri  Dinner     2            17.4
67         3.07   1.00  Female    Yes   Sat  Dinner     1            32.6
236       12.60   1.00    Male    Yes   Sat  Dinner     2             7.9

[244 rows x 8 columns]

In [164]:
df.to_csv('tips_for_HW_8.csv', index = False)